.dev.prog

diff --git a/linuxconf b/linuxconf
--- a/linuxconf
+++ b/linuxconf
@@ -1,7 +1,10 @@
 #!/bin/bash
 
+function echo2 () {
+    echo "$@" 1>&2
+}
 function err () {
-    echo "Error: $@" 1>&2
+    echo2 Error: "$@"
     return 1
 }
 function die () {
@@ -10,9 +13,27 @@ function die () {
 }
 
 lc_include conf.d/*
-function lc_include () {
 
+function lc_include () {
+    # for every included shell script, spawn sub shell,
+    #   in the subshell, source the script, call (eval) the function name specified by global variable $LCI_SUBSHELL_OP
+    # print the return code of the eval-ed function to stderr, but this function should always return success.
+
+    for script in "$@"; do
+        (
+            source "$script"
+            eval "$LCI_SUBSHELL_OP"
+        )
+        echo2 "$script -- $LCI_SUBSHELL_OP completed. return_val = $return_code"
+    done
+
+    return 0
 }
+
+# Example usage:
+# LCI_SUBSHELL_OP="your_function_name"
+# lc_include conf.d/*
+
 
 function lc_assert_user_is () {
     # todo
